
-------------------------------------------------------------------------------
|        ..          ..                                                       |
|       ####*.      ####.                                                     |
|         `###*.       `#.                 MSC Software                       |
|            `###.       #.                ------------                       |
|               `##.     ##                                                   |
|                 `##.   ##                                                   |
|                   `## ##'                A d a m s   C++   S o l v e r      |
|                     ####                 Build:        2017.0.0-CL454846    |
|                     ###.                 Version:      Adams 2017           |
|                    ###`#.                                                   |
|                  .###  `#                                                   |
|                 ####    `#                                                  |
|                ####      #.                                                 |
|              #####       `#              http://www.mscsoftware.com         |
|            .#####                                                           |
|           #####'                                                            |
|           ####                                                              |
|                                                                             |
|    *********************************************************************    |
|    *                                                                   *    |
|    *                      MSC Software Corporation                     *    |
|    *                                                                   *    |
|    *                             A d a m s                             *    |
|    *                                                                   *    |
|    *          Automatic Dynamic Analysis of Mechanical Systems         *    |
|    *                                                                   *    |
|    *********************************************************************    |
|    *                                                                   *    |
|    *                         LEGAL INFORMATION                         *    |
|    *                                                                   *    |
|    *  Warning:  This computer  program is protected  by copyright law  *    |
|    *  and  international  treaties.    Unauthorized  reproduction  or  *    |
|    *  distribution  of this  computer program, or any  portion of it,  *    |
|    *  may result in severe civil and criminal penalties.               *    |
|    *                                                                   *    |
|    *  Copyright (C) 2016 MSC Software Corporation and  its licensors.  *    |
|    *                        All rights reserved.                       *    |
|    *                                                                   *    |
|    *********************************************************************    |
|                                                                             |
|-----------------------------------------------------------------------------|
|                                                                             |
|    *********************************************************************    |
|    *                                                                   *    |
|    *   Local Time: 2020-11-01 13:48:44                                 *    |
|    *    Host Name: DESKTOP-BUO0R38                                     *    |
|    *        Uname: MS Windows NT                                       *    |
|    *      OS Info: 6.2                                                 *    |
|    *         User: hp                                                  *    |
|    *  Customer ID: B9846D1A-0BB5196A                                   *    |
|    *  Current dir: D:\Adams_experiment                                 *    |
|    *                                                                   *    |
|    *********************************************************************    |
|                                                                             |
-------------------------------------------------------------------------------

  OS-environment variable
  MDI_ADAMS_SCONTROLS_APPLICATION=1
  Adams Controls. Announces Adams Solver (C++) is being run with Adams Controls in either function evaluation mode or cosimulation mode.



-------------------------------------------------------------------------------
|                                 Model Title                                 |
|=============================================================================|
|                                                                             |
|                         SOLIDWORKS Motion Mechanism                         |
|                                                                             |
-------------------------------------------------------------------------------

 command: simulate/initial_conditions


  Begin Displacement Initial Conditions

  Time T=0.000000000E+00.
  Degree-of-freedom analysis identified redundant constraints in the model:
  -------------------------------------------------------------------------
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_3
   -  deactivating constraint equation  Zi.Yj in plant.Parallel1
   -  deactivating constraint equation  Zi.Xj in plant.Parallel1
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_2
   -  deactivating constraint equation  Zi.Yj in plant.Parallel8
   -  deactivating constraint equation  Zi.Xj in plant.Parallel8
   -  deactivating constraint equation  Zi.Xj in plant.Parallel5_3
   -  deactivating constraint equation  Zi.Yj in plant.Perpendicular1
   -  deactivating constraint equation  Zi.Xj in plant.Perpendicular1
   -  deactivating constraint equation  Zi.Yj in plant.Parallel8_2
   -  deactivating constraint equation  Zi.Xj in plant.Parallel8_2
   -  deactivating constraint equation  Zi.Yj in plant.Parallel2_2
   -  deactivating constraint equation  Zi.Xj in plant.Parallel2_2
   -  deactivating constraint equation  Zi.Yj in plant.Parallel7
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_5
   -  deactivating constraint equation  Zi.Yj in plant.Parallel3
   -  deactivating constraint equation  Zi.Yj in plant.Parallel7_2
   -  deactivating constraint equation  Zi.Yj in plant.Parallel5
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_4
   -  deactivating constraint equation  Xi.Yj in plant.Lock2
   -  deactivating constraint equation  Zi.Yj in plant.Lock2
   -  deactivating constraint equation  Zi.Xj in plant.Lock2
   -  deactivating constraint equation  Xi.Yj in plant.Lock1
   -  deactivating constraint equation  Zi.Yj in plant.Lock1
   -  deactivating constraint equation  Zi.Xj in plant.Lock1
   -  deactivating constraint equation  Xi.Yj in plant.Lock1_2
   -  deactivating constraint equation  Zi.Yj in plant.Lock1_2
   -  deactivating constraint equation  Zi.Xj in plant.Lock1_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident7_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident7_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident83
   -  deactivating constraint equation  Zi.Xj in plant.Coincident83
   -  deactivating constraint equation  Zi.Yj in plant.Coincident38
   -  deactivating constraint equation  Zi.Xj in plant.Coincident38
   -  deactivating constraint equation  Zi.Yj in plant.Coincident13
   -  deactivating constraint equation  Zi.Xj in plant.Coincident13
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10
   -  deactivating constraint equation  Zi.Xj in plant.Coincident10
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10_5
   -  deactivating constraint equation  Zi.Xj in plant.Coincident10_5
   -  deactivating constraint equation  Zi.Yj in plant.Coincident90
   -  deactivating constraint equation  Zi.Yj in plant.Coincident67
   -  deactivating constraint equation  Zi.Xj in plant.Coincident67
   -  deactivating constraint equation  Zi.Xj in plant.Coincident34
   -  deactivating constraint equation  Zi.Yj in plant.Coincident8
   -  deactivating constraint equation  Zi.Xj in plant.Coincident8
   -  deactivating constraint equation  Zi.Yj in plant.Coincident119
   -  deactivating constraint equation  Zi.Xj in plant.Coincident119
   -  deactivating constraint equation  Zi.Yj in plant.Coincident64
   -  deactivating constraint equation  Zi.Xj in plant.Coincident64
   -  deactivating constraint equation  Zi.Yj in plant.Distance2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident4_3
   -  deactivating constraint equation  Zi.Xj in plant.Coincident4_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident5
   -  deactivating constraint equation  Zi.Xj in plant.Coincident10_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident111
   -  deactivating constraint equation  Zi.Xj in plant.Coincident111
   -  deactivating constraint equation  Zi.Yj in plant.Coincident97
   -  deactivating constraint equation  Zi.Xj in plant.Coincident97
   -  deactivating constraint equation  Zi.Yj in plant.Coincident87
   -  deactivating constraint equation  Zi.Xj in plant.Coincident87
   -  deactivating constraint equation  Zi.Yj in plant.Coincident7
   -  deactivating constraint equation  Zi.Xj in plant.Coincident7
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10_4
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1_3
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident108
   -  deactivating constraint equation  Zi.Xj in plant.Coincident108
   -  deactivating constraint equation  Zi.Xj in plant.Coincident73
   -  deactivating constraint equation  Zi.Yj in plant.Coincident18
   -  deactivating constraint equation  Zi.Xj in plant.Coincident18
   -  deactivating constraint equation  Zi.Yj in plant.Coincident5_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident84
   -  deactivating constraint equation  Zi.Xj in plant.Coincident84
   -  deactivating constraint equation  Zi.Xj in plant.Coincident70
   -  deactivating constraint equation  Zi.Yj in plant.Coincident40
   -  deactivating constraint equation  Zi.Xj in plant.Coincident40
   -  deactivating constraint equation  Zi.Yj in plant.Coincident15
   -  deactivating constraint equation  Zi.Xj in plant.Coincident15
   -  deactivating constraint equation  Zi.Xj in plant.Coincident101
   -  deactivating constraint equation  Zi.Xj in plant.Coincident37
   -  deactivating constraint equation  Zi.Xj in plant.Coincident12
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident89
   -  deactivating constraint equation  Zi.Xj in plant.Coincident89
   -  deactivating constraint equation  Zi.Yj in plant.Coincident81
   -  deactivating constraint equation  Zi.Xj in plant.Coincident81
   -  deactivating constraint equation  Zi.Xj in plant.Coincident66
   -  deactivating constraint equation  Zi.Yj in plant.Coincident33
   -  deactivating constraint equation  Zi.Xj in plant.Coincident33
   -  deactivating constraint equation  Zi.Xj in plant.Coincident7_4
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident118
   -  deactivating constraint equation  Zi.Xj in plant.Coincident118
   -  deactivating constraint equation  Zi.Yj in plant.Coincident98
   -  deactivating constraint equation  Zi.Xj in plant.Coincident98
   -  deactivating constraint equation  Zi.Yj in plant.Coincident88
   -  deactivating constraint equation  Zi.Xj in plant.Coincident88
   -  deactivating constraint equation  Zi.Xj in plant.Coincident63
   -  deactivating constraint equation  Zi.Yj in plant.Coincident25
   -  deactivating constraint equation  Zi.Xj in plant.Coincident25
   -  deactivating constraint equation  Zi.Xj in plant.Coincident3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident6_3
   -  deactivating constraint equation  Zi.Xj in plant.Coincident6_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident110
   -  deactivating constraint equation  Zi.Xj in plant.Coincident110
   -  deactivating constraint equation  Zi.Yj in plant.Coincident96
   -  deactivating constraint equation  Zi.Xj in plant.Coincident96
   -  deactivating constraint equation  Zi.Yj in plant.Coincident4
   -  deactivating constraint equation  Zi.Xj in plant.Coincident4
   -  deactivating constraint equation  Zi.Yj in plant.Coincident107
   -  deactivating constraint equation  Zi.Xj in plant.Coincident107
   -  deactivating constraint equation  Zi.Yj in plant.Coincident85
   -  deactivating constraint equation  Zi.Xj in plant.Coincident85
   -  deactivating constraint equation  Zi.Yj in plant.Coincident72
   -  deactivating constraint equation  Zi.Xj in plant.Coincident72
   -  deactivating constraint equation  Zi.Xj in plant.Coincident43
   -  deactivating constraint equation  Zi.Yj in plant.Coincident17
   -  deactivating constraint equation  Zi.Xj in plant.Coincident17
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1
   -  deactivating constraint equation  Zi.Yj in plant.Coincident102
   -  deactivating constraint equation  Zi.Yj in plant.Coincident93
   -  deactivating constraint equation  Zi.Xj in plant.Coincident93
   -  deactivating constraint equation  Zi.Yj in plant.Coincident69
   -  deactivating constraint equation  Zi.Xj in plant.Coincident69
   -  deactivating constraint equation  Zi.Yj in plant.Coincident14
   -  deactivating constraint equation  Zi.Yj in plant.Coincident4_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident4_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident6_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident6_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident126
   -  deactivating constraint equation  Zi.Xj in plant.Coincident126
   -  deactivating constraint equation  Zi.Yj in plant.Coincident82
   -  deactivating constraint equation  Zi.Xj in plant.Coincident82
   -  deactivating constraint equation  Zi.Yj in plant.Coincident35
   -  deactivating constraint equation  Zi.Xj in plant.Coincident9
   -  deactivating constraint equation  Zi.Yj in plant.Coincident99
   -  deactivating constraint equation  Zi.Xj in plant.Coincident99
   -  deactivating constraint equation  Zi.Yj in plant.Coincident7_3
   -  deactivating constraint equation  Zi.Xj in plant.Coincident7_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident116
   -  deactivating constraint equation  Zi.Xj in plant.Coincident116
   -  deactivating constraint equation  Zi.Yj in plant.Coincident56
   -  deactivating constraint equation  Zi.Xj in plant.Coincident56
   -  deactivating constraint equation  Zi.Yj in plant.Coincident9_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident9_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident109
   -  deactivating constraint equation  Zi.Xj in plant.Coincident109
   -  deactivating constraint equation  Zi.Yj in plant.Coincident86
   -  deactivating constraint equation  Zi.Xj in plant.Coincident86
   -  deactivating constraint equation  Zi.Yj in plant.Coincident74
   -  deactivating constraint equation  Zi.Xj in plant.Coincident74
   -  deactivating constraint equation  Zi.Yj in plant.Coincident19
   -  deactivating constraint equation  Zi.Yj in plant.Coincident6
   -  deactivating constraint equation  Zi.Xj in plant.Coincident6
   -  deactivating constraint equation  Zi.Yj in plant.Coincident103
   -  deactivating constraint equation  Zi.Xj in plant.Coincident103
   -  deactivating constraint equation  Zi.Xj in plant.Concentric47
   -  deactivating constraint equation  Zi.Yj in plant.Concentric17
   -  deactivating constraint equation  Zi.Xj in plant.Concentric17
   -  deactivating constraint equation  Si.Xj in plant.Concentric17
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric2_2
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_4
   -  deactivating constraint equation  Zi.Xj in plant.Concentric2_4
   -  deactivating constraint equation  Zi.Yj in plant.Concentric46
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5_5
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5_5
   -  deactivating constraint equation  Zi.Yj in plant.Concentric25
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_6
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_3
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5_4
   -  deactivating constraint equation  Zi.Xj in plant.Concentric3_2
   -  deactivating constraint equation  Zi.Yj in plant.Concentric37
   -  deactivating constraint equation  Zi.Xj in plant.Concentric37
   -  deactivating constraint equation  Zi.Xj in plant.Concentric8
   -  deactivating constraint equation  Zi.Yj in plant.Concentric45
   -  deactivating constraint equation  Zi.Xj in plant.Concentric45
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5
   -  deactivating constraint equation  Zi.Yj in plant.Concentric8_2
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5_3
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5_3
   -  deactivating constraint equation  Zi.Xj in plant.Concentric3
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric4_4
   -  deactivating constraint equation  Zi.Xj in plant.Concentric9_3
   -  deactivating constraint equation  Zi.Xj in plant.Concentric35
   -  deactivating constraint equation  Zi.Xj in plant.Concentric7
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_5
   -  deactivating constraint equation  Zi.Xj in plant.Concentric13
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric2
  Time T=0.000000000E+00.
  Degree-of-freedom analysis identified redundant constraints in the model:
  -------------------------------------------------------------------------
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_3
   -  deactivating constraint equation  Zi.Yj in plant.Parallel1
   -  deactivating constraint equation  Zi.Xj in plant.Parallel1
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_2
   -  deactivating constraint equation  Zi.Yj in plant.Parallel8
   -  deactivating constraint equation  Zi.Xj in plant.Parallel8
   -  deactivating constraint equation  Zi.Yj in plant.Perpendicular1
   -  deactivating constraint equation  Zi.Xj in plant.Perpendicular1
   -  deactivating constraint equation  Zi.Yj in plant.Parallel2_2
   -  deactivating constraint equation  Zi.Yj in plant.Parallel5_2
   -  deactivating constraint equation  Zi.Yj in plant.Parallel7
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_5
   -  deactivating constraint equation  Zi.Yj in plant.Parallel3
   -  deactivating constraint equation  Zi.Yj in plant.Parallel6_4
   -  deactivating constraint equation  Xi.Yj in plant.Lock2
   -  deactivating constraint equation  Zi.Yj in plant.Lock2
   -  deactivating constraint equation  Zi.Xj in plant.Lock2
   -  deactivating constraint equation  Xi.Yj in plant.Lock1
   -  deactivating constraint equation  Zi.Yj in plant.Lock1
   -  deactivating constraint equation  Zi.Xj in plant.Lock1
   -  deactivating constraint equation  Xi.Yj in plant.Lock1_2
   -  deactivating constraint equation  Zi.Yj in plant.Lock1_2
   -  deactivating constraint equation  Zi.Xj in plant.Lock1_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident7_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident92
   -  deactivating constraint equation  Zi.Yj in plant.Coincident83
   -  deactivating constraint equation  Zi.Xj in plant.Coincident83
   -  deactivating constraint equation  Zi.Yj in plant.Coincident38
   -  deactivating constraint equation  Zi.Xj in plant.Coincident38
   -  deactivating constraint equation  Zi.Yj in plant.Coincident13
   -  deactivating constraint equation  Zi.Xj in plant.Coincident13
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10
   -  deactivating constraint equation  Zi.Xj in plant.Coincident10
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10_5
   -  deactivating constraint equation  Zi.Xj in plant.Coincident10_5
   -  deactivating constraint equation  Zi.Xj in plant.Coincident90
   -  deactivating constraint equation  Zi.Yj in plant.Coincident67
   -  deactivating constraint equation  Zi.Xj in plant.Coincident67
   -  deactivating constraint equation  Zi.Xj in plant.Coincident34
   -  deactivating constraint equation  Zi.Yj in plant.Coincident8
   -  deactivating constraint equation  Zi.Xj in plant.Coincident8
   -  deactivating constraint equation  Zi.Yj in plant.Coincident119
   -  deactivating constraint equation  Zi.Xj in plant.Coincident119
   -  deactivating constraint equation  Zi.Yj in plant.Coincident64
   -  deactivating constraint equation  Zi.Xj in plant.Coincident64
   -  deactivating constraint equation  Zi.Yj in plant.Distance2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident4_3
   -  deactivating constraint equation  Zi.Xj in plant.Coincident4_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident5
   -  deactivating constraint equation  Zi.Xj in plant.Coincident5
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident10_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident111
   -  deactivating constraint equation  Zi.Xj in plant.Coincident111
   -  deactivating constraint equation  Zi.Yj in plant.Coincident97
   -  deactivating constraint equation  Zi.Xj in plant.Coincident97
   -  deactivating constraint equation  Zi.Yj in plant.Coincident87
   -  deactivating constraint equation  Zi.Xj in plant.Coincident87
   -  deactivating constraint equation  Zi.Yj in plant.Coincident7
   -  deactivating constraint equation  Zi.Xj in plant.Coincident7
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10_4
   -  deactivating constraint equation  Zi.Xj in plant.Coincident10_4
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1_3
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident108
   -  deactivating constraint equation  Zi.Xj in plant.Coincident108
   -  deactivating constraint equation  Zi.Xj in plant.Coincident73
   -  deactivating constraint equation  Zi.Yj in plant.Coincident18
   -  deactivating constraint equation  Zi.Xj in plant.Coincident18
   -  deactivating constraint equation  Zi.Yj in plant.Coincident5_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident5_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident84
   -  deactivating constraint equation  Zi.Xj in plant.Coincident84
   -  deactivating constraint equation  Zi.Xj in plant.Coincident70
   -  deactivating constraint equation  Zi.Yj in plant.Coincident40
   -  deactivating constraint equation  Zi.Xj in plant.Coincident40
   -  deactivating constraint equation  Zi.Yj in plant.Coincident15
   -  deactivating constraint equation  Zi.Xj in plant.Coincident15
   -  deactivating constraint equation  Zi.Xj in plant.Coincident101
   -  deactivating constraint equation  Zi.Yj in plant.Coincident37
   -  deactivating constraint equation  Zi.Xj in plant.Coincident37
   -  deactivating constraint equation  Zi.Xj in plant.Coincident12
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident89
   -  deactivating constraint equation  Zi.Xj in plant.Coincident89
   -  deactivating constraint equation  Zi.Yj in plant.Coincident81
   -  deactivating constraint equation  Zi.Xj in plant.Coincident81
   -  deactivating constraint equation  Zi.Xj in plant.Coincident66
   -  deactivating constraint equation  Zi.Yj in plant.Coincident33
   -  deactivating constraint equation  Zi.Xj in plant.Coincident33
   -  deactivating constraint equation  Zi.Xj in plant.Coincident7_4
   -  deactivating constraint equation  Zi.Yj in plant.Coincident10_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident118
   -  deactivating constraint equation  Zi.Xj in plant.Coincident118
   -  deactivating constraint equation  Zi.Yj in plant.Coincident98
   -  deactivating constraint equation  Zi.Yj in plant.Coincident88
   -  deactivating constraint equation  Zi.Xj in plant.Coincident88
   -  deactivating constraint equation  Zi.Xj in plant.Coincident63
   -  deactivating constraint equation  Zi.Yj in plant.Coincident25
   -  deactivating constraint equation  Zi.Xj in plant.Coincident25
   -  deactivating constraint equation  Zi.Xj in plant.Coincident3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident6_3
   -  deactivating constraint equation  Zi.Xj in plant.Coincident6_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident110
   -  deactivating constraint equation  Zi.Xj in plant.Coincident110
   -  deactivating constraint equation  Zi.Yj in plant.Coincident96
   -  deactivating constraint equation  Zi.Yj in plant.Coincident4
   -  deactivating constraint equation  Zi.Xj in plant.Coincident4
   -  deactivating constraint equation  Zi.Yj in plant.Coincident107
   -  deactivating constraint equation  Zi.Xj in plant.Coincident107
   -  deactivating constraint equation  Zi.Yj in plant.Coincident85
   -  deactivating constraint equation  Zi.Xj in plant.Coincident85
   -  deactivating constraint equation  Zi.Yj in plant.Coincident72
   -  deactivating constraint equation  Zi.Xj in plant.Coincident72
   -  deactivating constraint equation  Zi.Xj in plant.Coincident43
   -  deactivating constraint equation  Zi.Yj in plant.Coincident17
   -  deactivating constraint equation  Zi.Xj in plant.Coincident17
   -  deactivating constraint equation  Zi.Yj in plant.Coincident1
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1
   -  deactivating constraint equation  Zi.Yj in plant.Coincident102
   -  deactivating constraint equation  Zi.Yj in plant.Coincident93
   -  deactivating constraint equation  Zi.Xj in plant.Coincident93
   -  deactivating constraint equation  Zi.Yj in plant.Coincident69
   -  deactivating constraint equation  Zi.Xj in plant.Coincident69
   -  deactivating constraint equation  Zi.Yj in plant.Coincident14
   -  deactivating constraint equation  Zi.Xj in plant.Coincident14
   -  deactivating constraint equation  Zi.Yj in plant.Coincident4_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident4_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident6_2
   -  deactivating constraint equation  Zi.Xj in plant.Coincident6_2
   -  deactivating constraint equation  Zi.Yj in plant.Coincident126
   -  deactivating constraint equation  Zi.Xj in plant.Coincident126
   -  deactivating constraint equation  Zi.Yj in plant.Coincident82
   -  deactivating constraint equation  Zi.Xj in plant.Coincident82
   -  deactivating constraint equation  Zi.Xj in plant.Coincident35
   -  deactivating constraint equation  Zi.Xj in plant.Coincident9
   -  deactivating constraint equation  Zi.Xj in plant.Coincident99
   -  deactivating constraint equation  Zi.Xj in plant.Coincident7_3
   -  deactivating constraint equation  Zi.Yj in plant.Coincident116
   -  deactivating constraint equation  Zi.Xj in plant.Coincident116
   -  deactivating constraint equation  Zi.Yj in plant.Coincident56
   -  deactivating constraint equation  Zi.Xj in plant.Coincident56
   -  deactivating constraint equation  Zi.Xj in plant.Coincident1_4
   -  deactivating constraint equation  Zi.Yj in plant.Coincident109
   -  deactivating constraint equation  Zi.Xj in plant.Coincident109
   -  deactivating constraint equation  Zi.Yj in plant.Coincident86
   -  deactivating constraint equation  Zi.Xj in plant.Coincident86
   -  deactivating constraint equation  Zi.Yj in plant.Coincident74
   -  deactivating constraint equation  Zi.Xj in plant.Coincident74
   -  deactivating constraint equation  Zi.Yj in plant.Coincident6
   -  deactivating constraint equation  Zi.Yj in plant.Coincident103
   -  deactivating constraint equation  Zi.Xj in plant.Coincident103
   -  deactivating constraint equation  Zi.Yj in plant.Concentric4_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric4_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric47
   -  deactivating constraint equation  Zi.Yj in plant.Concentric17
   -  deactivating constraint equation  Zi.Xj in plant.Concentric17
   -  deactivating constraint equation  Si.Xj in plant.Concentric17
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric2_2
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_4
   -  deactivating constraint equation  Zi.Yj in plant.Concentric46
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5_5
   -  deactivating constraint equation  Zi.Yj in plant.Concentric44
   -  deactivating constraint equation  Zi.Yj in plant.Concentric34
   -  deactivating constraint equation  Zi.Xj in plant.Concentric9
   -  deactivating constraint equation  Zi.Yj in plant.Concentric3_3
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_3
   -  deactivating constraint equation  Zi.Xj in plant.Concentric2_3
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5_4
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5_4
   -  deactivating constraint equation  Zi.Xj in plant.Concentric3_2
   -  deactivating constraint equation  Zi.Yj in plant.Concentric45
   -  deactivating constraint equation  Zi.Xj in plant.Concentric45
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5
   -  deactivating constraint equation  Zi.Yj in plant.Concentric8_2
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5_3
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5_3
   -  deactivating constraint equation  Zi.Xj in plant.Concentric3
   -  deactivating constraint equation  Zi.Yj in plant.Concentric5_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric5_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric9_3
   -  deactivating constraint equation  Zi.Yj in plant.Concentric35
   -  deactivating constraint equation  Zi.Xj in plant.Concentric43
   -  deactivating constraint equation  Zi.Yj in plant.Concentric3_4
   -  deactivating constraint equation  Zi.Xj in plant.Concentric4
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2_5
   -  deactivating constraint equation  Zi.Xj in plant.Concentric2_5
   -  deactivating constraint equation  Zi.Xj in plant.Concentric42
   -  deactivating constraint equation  Zi.Yj in plant.Concentric2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric7_2
   -  deactivating constraint equation  Zi.Xj in plant.Concentric9_2

  End Displacement Initial Conditions


  Begin Velocity Initial Conditions


  End Velocity Initial Conditions


  Begin Acceleration Initial Conditions


  End Acceleration Initial Conditions


Finished -----
Elapsed time = 3.65s,  CPU time = 0.23s,  6.43%
